name: Feature Request
description: Suggest an idea to this project
title: "[Feature]: "
labels: [feature]
assignees:
  - CesarTrigo
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this feature request. Our team will review it and come back to you.
  - type: input
    id: contact
    attributes:
      label: Contact details
      description: How can we get in touch with you if we need more info?
      placeholder: Ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem or need? Please describe.
      description: A clear and concise description of what the problem or need is.
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Ex. I would like to have a functionality that allows [...]
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Description of any alternative solutions or features you've considered.
      placeholder: As an alternative it would be great to have an API endpoint [...]
    validations:
      required: false
  - type: textarea
    id: aditional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
